version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "choonja"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    restart: always
    depends_on:
      - db
    command:
      [
        "dockerize",
        "-wait",
        "tcp://db:3306",
        "-timeout",
        "30s",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  db_data:
